# Generated by Django 2.0.5 on 2018-10-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20181015_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='courses',
            field=models.ManyToManyField(through='first_app.CourseIdSubjectId', to='first_app.Course'),
        ),
    ]
