# Generated by Django 2.0.5 on 2018-10-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_subject_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ManyToManyField(through='first_app.CourseIdSubjectId', to='first_app.Subject'),
        ),
    ]
