# Generated by Django 2.0.5 on 2018-10-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_remove_course_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('teacher_name', models.CharField(max_length=30)),
                ('study_time', models.DateField()),
                ('week', models.CharField(max_length=30)),
            ],
        ),
    ]
